substitutions:
  _FRONT_IMAGE: us-east1-docker.pkg.dev/${PROJECT_ID}/open-adoption/front:${COMMIT_SHA}

images:
  - "${_FRONT_IMAGE}"

options:
  logging: CLOUD_LOGGING_ONLY
  
steps:
  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      ["gsutil", "cp", "gs://${_STORAGE_BUCKET}/front/environment.ts", "/workspace/src/environments/"]

  - name: "gcr.io/cloud-builders/docker"
    args: ["build", "-t", "${_FRONT_IMAGE}",  "."]

  - name: "gcr.io/cloud-builders/docker"
    args: ["push", "${_FRONT_IMAGE}"]

  - name: "gcr.io/google.com/cloudsdktool/cloud-sdk:slim"
    args:
      [
        "gcloud", "run", "deploy", "open-adoption-front",
        "--image", "${_FRONT_IMAGE}",
        "--region", "us-east1",
        "--cpu", "${_CPUS}",
        "--memory", "${_MEMORY}",
        "--min-instances", "${_MIN_INSTANCES}",
        "--max-instances", "${_MAX_INSTANCES}",
        "--port", "80",
        "--allow-unauthenticated",
        "--platform", "managed",
        "--use-http2"
      ]
        
